//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.shared
{
    public partial class email_test
    {
        protected global::System.Web.UI.WebControls.Panel ResultOkPanel;
        protected global::System.Web.UI.WebControls.Panel ResultErrorPanel;
        protected global::System.Web.UI.WebControls.Literal ErrorText;
        protected global::System.Web.UI.WebControls.TextBox ToBox;
        protected global::System.Web.UI.WebControls.DropDownList TemplateDropDown;
        protected global::System.Web.UI.WebControls.TextBox StudentNameBox;
        protected global::System.Web.UI.WebControls.TextBox StudentEmailBox;
        protected global::System.Web.UI.WebControls.TextBox TempPasswordBox;
        protected global::System.Web.UI.WebControls.TextBox ResetUrlBox;
        protected global::System.Web.UI.WebControls.TextBox TitleBox;
        protected global::System.Web.UI.WebControls.TextBox DetailBox;
        protected global::System.Web.UI.WebControls.TextBox PdfPathBox;
        protected global::System.Web.UI.WebControls.Button SendButton;
    }
}
