//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.devtools
{
    public partial class ai_console
    {
        protected global::System.Web.UI.WebControls.Panel gatePanel;
        protected global::System.Web.UI.WebControls.TextBox passwordBox;
        protected global::System.Web.UI.WebControls.Button enterBtn;
        protected global::System.Web.UI.WebControls.Label gateError;
        protected global::System.Web.UI.WebControls.Panel consolePanel;
        protected global::System.Web.UI.WebControls.Button logoutBtn;
        protected global::System.Web.UI.WebControls.TextBox baseUrlBox;
        protected global::System.Web.UI.WebControls.TextBox apiKeyBox;
        protected global::System.Web.UI.WebControls.TextBox modelBox;
        protected global::System.Web.UI.WebControls.Button saveBtn;
        protected global::System.Web.UI.WebControls.Button resetBtn;
        protected global::System.Web.UI.WebControls.Label saveMsg;
        protected global::System.Web.UI.WebControls.Button refreshBtn;
        protected global::System.Web.UI.WebControls.Repeater logsRepeater;
        protected global::System.Web.UI.WebControls.Label emptyLabel;
    }
}
