//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.admin
{


    public partial class academic_performance
    {
        /// <summary>btnSendWarnings control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSendWarnings;

        /// <summary>pnlResult control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlResult;

        /// <summary>litResult control.</summary>
        protected global::System.Web.UI.WebControls.Literal litResult;
    }
}