<%@ Page Language="C#" MasterPageFile="~/admin/AdminLayout.master" AutoEventWireup="true" CodeBehind="academic_performance.aspx.cs" Inherits="src.admin.academic_performance" Title="Academic Performance - INTI Admin Portal" %>
<asp:Content ContentPlaceHolderID="MainContent" runat="server">

    <div class="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
        <div>
            <p class="text-slate-500" style="font-size:13px;font-weight:500">Admin</p>
            <h1 class="mt-1 text-slate-900" style="font-size:28px;font-weight:700;letter-spacing:-0.01em">Academic Performance</h1>
            <p class="mt-1 text-slate-500" style="font-size:14px">Analyse grades, attendance, and student outcomes across programmes and semesters.</p>
        </div>
        <div class="flex flex-wrap items-center gap-2">
            <div class="relative" data-dropdown>
                <button type="button" data-dropdown-toggle class="inline-flex items-center gap-1.5 rounded-md border border-slate-200 bg-white px-3 h-10 text-slate-700 hover:bg-slate-50 transition-colors" style="font-size:13px;font-weight:600"><i data-lucide="filter" class="h-4 w-4"></i> Filter</button>
                <div data-dropdown-menu style="display:none" class="absolute right-0 z-20 mt-2 w-80 rounded-xl border border-slate-200 bg-white p-4 shadow-lg">
                    <div class="text-slate-900" style="font-size:13px;font-weight:700">Scope</div>
                    <p class="mt-0.5 text-slate-500" style="font-size:12px">Applied across every tab.</p>
                    <div class="mt-3 space-y-3">
                        <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Academic Year</span><div class="mt-1.5"><select class="h-9 w-full rounded-md border border-slate-200 bg-white px-3 text-slate-700 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px"><%= AcademicYearOptionsHtml %></select></div></label>
                        <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Semester</span><div class="mt-1.5"><select class="h-9 w-full rounded-md border border-slate-200 bg-white px-3 text-slate-700 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px"><%= SemesterOptionsHtml %></select></div></label>
                        <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Programme</span><div class="mt-1.5"><select class="h-9 w-full rounded-md border border-slate-200 bg-white px-3 text-slate-700 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px"><%= ProgrammeOptionsHtml %></select></div></label>
                    </div>
                    <div class="mt-4 flex items-center justify-between">
                        <button type="button" class="text-slate-500 hover:text-slate-900" style="font-size:12px;font-weight:600">Clear</button>
                        <button type="button" data-toast="Scope filtering is not connected yet" data-toast-type="info" class="inline-flex items-center rounded-md bg-[#e0162b] px-4 h-10 text-white hover:bg-[#a01020]" style="font-size:13px;font-weight:600">Apply</button>
                    </div>
                </div>
            </div>
            <div class="relative" data-dropdown>
                <button type="button" data-dropdown-toggle class="inline-flex items-center gap-1.5 rounded-md border border-slate-200 bg-white px-3 h-10 text-slate-700 hover:bg-slate-50 transition-colors" style="font-size:13px;font-weight:600"><i data-lucide="download" class="h-4 w-4"></i> Export Report <i data-lucide="chevron-down" class="h-3.5 w-3.5"></i></button>
                <div data-dropdown-menu style="display:none" class="absolute right-0 z-20 mt-2 w-48 rounded-xl border border-slate-200 bg-white p-1 shadow-lg">
                    <button type="button" data-toast="Use Reports to generate downloadable files" data-toast-type="info" class="flex w-full items-center gap-2 rounded-md px-3 py-2 text-left text-slate-700 hover:bg-slate-50" style="font-size:13px;font-weight:500"><i data-lucide="file-text" class="h-4 w-4 text-[#e0162b]"></i> Export as PDF</button>
                    <button type="button" data-toast="Use Reports to generate downloadable files" data-toast-type="info" class="flex w-full items-center gap-2 rounded-md px-3 py-2 text-left text-slate-700 hover:bg-slate-50" style="font-size:13px;font-weight:500"><i data-lucide="file-spreadsheet" class="h-4 w-4 text-emerald-600"></i> Export as Excel</button>
                </div>
            </div>
        </div>
    </div>

    <%-- KPI strip --%>
    <section class="mt-6" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:16px">
        <div class="rounded-2xl border border-slate-200 bg-white p-4 hover:border-slate-300 hover:shadow-sm transition-all"><div class="flex items-center justify-between"><div class="text-slate-500" style="font-size:11.5px;font-weight:500">Average GPA</div><i data-lucide="trending-up" class="h-4 w-4 text-slate-300"></i></div><div class="mt-1 text-slate-900" style="font-size:22px;font-weight:700;letter-spacing:-0.01em"><%= DecimalNumber(Summary.AverageCgpa) %></div><div class="text-slate-400" style="font-size:11.5px">Current semester</div><div class="mt-2 h-1 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-slate-400" style="width:62%"></div></div></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-4 hover:border-slate-300 hover:shadow-sm transition-all"><div class="flex items-center justify-between"><div class="text-slate-500" style="font-size:11.5px;font-weight:500">Average CGPA</div><i data-lucide="graduation-cap" class="h-4 w-4 text-slate-300"></i></div><div class="mt-1 text-slate-900" style="font-size:22px;font-weight:700;letter-spacing:-0.01em"><%= DecimalNumber(Summary.AverageCgpa) %></div><div class="text-slate-400" style="font-size:11.5px">Cumulative average</div><div class="mt-2 h-1 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-slate-400" style="width:64%"></div></div></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-4 hover:border-slate-300 hover:shadow-sm transition-all"><div class="flex items-center justify-between"><div class="text-slate-500" style="font-size:11.5px;font-weight:500">Pass Rate</div><i data-lucide="check-circle-2" class="h-4 w-4 text-slate-300"></i></div><div class="mt-1 text-emerald-600" style="font-size:22px;font-weight:700;letter-spacing:-0.01em"><%= Percent(Summary.PassRate) %></div><div class="text-slate-400" style="font-size:11.5px">Across all courses</div><div class="mt-2 h-1 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-emerald-500" style="width:86%"></div></div></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-4 hover:border-slate-300 hover:shadow-sm transition-all"><div class="flex items-center justify-between"><div class="text-slate-500" style="font-size:11.5px;font-weight:500">Fail Rate</div><i data-lucide="x-circle" class="h-4 w-4 text-slate-300"></i></div><div class="mt-1 text-[#a01020]" style="font-size:22px;font-weight:700;letter-spacing:-0.01em"><%= Percent(Summary.FailRate) %></div><div class="text-slate-400" style="font-size:11.5px">Across all courses</div><div class="mt-2 h-1 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-[#e0162b]" style="width:14%"></div></div></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-4 hover:border-slate-300 hover:shadow-sm transition-all"><div class="flex items-center justify-between"><div class="text-slate-500" style="font-size:11.5px;font-weight:500">At-Risk Students</div><i data-lucide="alert-triangle" class="h-4 w-4 text-slate-300"></i></div><div class="mt-1 text-[#a01020]" style="font-size:22px;font-weight:700;letter-spacing:-0.01em"><%= Summary.AtRiskStudents.ToString("N0") %></div><div class="text-slate-400" style="font-size:11.5px">Intervention required</div><div class="mt-2 h-1 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-[#e0162b]" style="width:24%"></div></div></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-4 hover:border-slate-300 hover:shadow-sm transition-all"><div class="flex items-center justify-between"><div class="text-slate-500" style="font-size:11.5px;font-weight:500">Top Performers</div><i data-lucide="award" class="h-4 w-4 text-slate-300"></i></div><div class="mt-1 text-emerald-600" style="font-size:22px;font-weight:700;letter-spacing:-0.01em">112</div><div class="text-slate-400" style="font-size:11.5px">CGPA &ge; 3.7</div><div class="mt-2 h-1 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-emerald-500" style="width:88%"></div></div></div>
    </section>

    <%-- Tab card --%>
    <section class="mt-6 rounded-lg border border-slate-200 bg-white" data-tabs>
        <div class="flex flex-wrap gap-1 border-b border-slate-100 px-4 pt-3">
            <button type="button" data-tab="overview" class="inline-flex items-center gap-2 rounded-t-lg border-b-2 border-transparent px-3 py-2 text-slate-500 hover:text-slate-900 data-[active=true]:border-[#e0162b] data-[active=true]:text-[#a01020]" style="font-size:13px;font-weight:600">Result Overview</button>
            <button type="button" data-tab="students" class="inline-flex items-center gap-2 rounded-t-lg border-b-2 border-transparent px-3 py-2 text-slate-500 hover:text-slate-900 data-[active=true]:border-[#e0162b] data-[active=true]:text-[#a01020]" style="font-size:13px;font-weight:600">Student Results</button>
            <button type="button" data-tab="passfail" class="inline-flex items-center gap-2 rounded-t-lg border-b-2 border-transparent px-3 py-2 text-slate-500 hover:text-slate-900 data-[active=true]:border-[#e0162b] data-[active=true]:text-[#a01020]" style="font-size:13px;font-weight:600">Pass/Fail Analysis</button>
            <button type="button" data-tab="attendance" class="inline-flex items-center gap-2 rounded-t-lg border-b-2 border-transparent px-3 py-2 text-slate-500 hover:text-slate-900 data-[active=true]:border-[#e0162b] data-[active=true]:text-[#a01020]" style="font-size:13px;font-weight:600">Attendance</button>
            <button type="button" data-tab="atrisk" class="inline-flex items-center gap-2 rounded-t-lg border-b-2 border-transparent px-3 py-2 text-slate-500 hover:text-slate-900 data-[active=true]:border-[#e0162b] data-[active=true]:text-[#a01020]" style="font-size:13px;font-weight:600">At-Risk Students</button>
            <button type="button" data-tab="top" class="inline-flex items-center gap-2 rounded-t-lg border-b-2 border-transparent px-3 py-2 text-slate-500 hover:text-slate-900 data-[active=true]:border-[#e0162b] data-[active=true]:text-[#a01020]" style="font-size:13px;font-weight:600">Top Performers</button>
        </div>

        <%-- Overview --%>
        <div data-tab-panel="overview">
            <div class="p-6" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:24px">
                <div class="rounded-xl border border-slate-200 p-5">
                    <h3 class="text-slate-900" style="font-size:14px;font-weight:700">Grade Distribution</h3>
                    <p class="mt-0.5 text-slate-500" style="font-size:12px">Letter grades across the current semester.</p>
                    <div class="mt-4 space-y-3">
                        <div><div class="flex items-center justify-between" style="font-size:12.5px"><span class="text-slate-700 font-medium">A / A+</span><span class="text-slate-500 tabular-nums">32%</span></div><div class="mt-1 h-2 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-emerald-500" style="width:32%"></div></div></div>
                        <div><div class="flex items-center justify-between" style="font-size:12.5px"><span class="text-slate-700 font-medium">B / B+</span><span class="text-slate-500 tabular-nums">38%</span></div><div class="mt-1 h-2 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-sky-500" style="width:38%"></div></div></div>
                        <div><div class="flex items-center justify-between" style="font-size:12.5px"><span class="text-slate-700 font-medium">C / C+</span><span class="text-slate-500 tabular-nums">16%</span></div><div class="mt-1 h-2 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-amber-500" style="width:16%"></div></div></div>
                        <div><div class="flex items-center justify-between" style="font-size:12.5px"><span class="text-slate-700 font-medium">D</span><span class="text-slate-500 tabular-nums">8%</span></div><div class="mt-1 h-2 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-orange-500" style="width:8%"></div></div></div>
                        <div><div class="flex items-center justify-between" style="font-size:12.5px"><span class="text-slate-700 font-medium">F</span><span class="text-slate-500 tabular-nums">6%</span></div><div class="mt-1 h-2 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-[#e0162b]" style="width:6%"></div></div></div>
                    </div>
                </div>
                <div class="rounded-xl border border-slate-200 p-5">
                    <h3 class="text-slate-900" style="font-size:14px;font-weight:700">Pass Rate by Programme</h3>
                    <p class="mt-0.5 text-slate-500" style="font-size:12px">Programme comparison across the cohort.</p>
                    <div class="mt-4 space-y-3">
                        <div><div class="flex items-center justify-between" style="font-size:12.5px"><span class="text-slate-700 font-medium">BCS</span><span class="text-slate-500 tabular-nums">89%</span></div><div class="mt-1 h-2 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-[#e0162b]" style="width:89%"></div></div></div>
                        <div><div class="flex items-center justify-between" style="font-size:12.5px"><span class="text-slate-700 font-medium">BIT</span><span class="text-slate-500 tabular-nums">84%</span></div><div class="mt-1 h-2 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-[#e0162b]" style="width:84%"></div></div></div>
                        <div><div class="flex items-center justify-between" style="font-size:12.5px"><span class="text-slate-700 font-medium">BBA</span><span class="text-slate-500 tabular-nums">88%</span></div><div class="mt-1 h-2 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-[#e0162b]" style="width:88%"></div></div></div>
                        <div><div class="flex items-center justify-between" style="font-size:12.5px"><span class="text-slate-700 font-medium">BME</span><span class="text-slate-500 tabular-nums">80%</span></div><div class="mt-1 h-2 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-[#e0162b]" style="width:80%"></div></div></div>
                        <div><div class="flex items-center justify-between" style="font-size:12.5px"><span class="text-slate-700 font-medium">BDS</span><span class="text-slate-500 tabular-nums">92%</span></div><div class="mt-1 h-2 w-full overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-[#e0162b]" style="width:92%"></div></div></div>
                    </div>
                </div>
            </div>
        </div>

        <%-- Student Results --%>
        <div data-tab-panel="students">
            <div data-table data-page-size="20">
                <div class="flex flex-col gap-3 px-6 py-4 lg:flex-row lg:items-center lg:justify-between">
                    <div class="relative w-full lg:max-w-sm">
                        <svg viewBox="0 0 24 24" class="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7" /><path d="m21 21-4.3-4.3" /></svg>
                        <input data-table-search placeholder="Search student, ID or course&hellip;" class="h-9 w-full rounded-md border border-slate-200 bg-white pl-9 pr-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px" />
                    </div>
                    <div class="flex flex-wrap items-center gap-2">
                        <select data-table-filter="prog" class="h-9 rounded-md border border-slate-200 bg-white px-3 text-slate-700 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px"><%= ProgrammeOptionsHtml %></select>
                        <select data-table-filter="sem" class="h-9 rounded-md border border-slate-200 bg-white px-3 text-slate-700 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px"><%= SemesterOptionsHtml %></select>
                        <div data-table-chip="status" class="inline-flex items-center rounded-md border border-slate-200 bg-white p-0.5">
                            <button type="button" data-chip="All" data-active="true" class="rounded px-2.5 py-1 text-slate-600 hover:text-slate-900 data-[active=true]:bg-[#e0162b]/10 data-[active=true]:text-[#a01020]" style="font-size:11.5px;font-weight:600">All</button>
                            <button type="button" data-chip="Pass" class="rounded px-2.5 py-1 text-slate-600 hover:text-slate-900 data-[active=true]:bg-[#e0162b]/10 data-[active=true]:text-[#a01020]" style="font-size:11.5px;font-weight:600">Pass</button>
                            <button type="button" data-chip="Fail" class="rounded px-2.5 py-1 text-slate-600 hover:text-slate-900 data-[active=true]:bg-[#e0162b]/10 data-[active=true]:text-[#a01020]" style="font-size:11.5px;font-weight:600">Fail</button>
                        </div>
                    </div>
                </div>
                <div class="overflow-x-auto">
                    <table class="min-w-full">
                        <thead class="border-y border-slate-100 bg-slate-50/60 text-slate-500"><tr>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">ID</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Name</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Prog</th><th class="px-6 py-3 text-center uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Sem</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Course</th><th class="px-6 py-3 text-center uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Grade</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">GPA</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">CGPA</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Status</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Action</th>
                        </tr></thead>
                        <tbody>
                            <tr data-row data-search="s12039 lim wei jian csc2024" data-prog="BCS" data-sem="4" data-status="Pass" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3 text-slate-500" style="font-size:12.5px">S12039</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">Lim Wei Jian</span></td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BCS</span></td><td class="px-6 py-3 text-slate-700 text-center" style="font-size:12.5px">4</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px"><span class="text-slate-900 font-medium">CSC2024</span> &middot; Mobile App Dev</td><td class="px-6 py-3 text-center" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-emerald-50 text-emerald-700 border-emerald-100" style="font-size:11.5px;font-weight:600">A</span></td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">4.00</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">3.75</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-emerald-50 text-emerald-700 border-emerald-100" style="font-size:11.5px;font-weight:600">Pass</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><a href="<%= ResolveUrl("~/admin/student_detail.aspx?id=S12039") %>" class="inline-flex h-7 items-center rounded-md border border-slate-200 bg-white px-2 text-slate-600 hover:bg-slate-50" style="font-size:11.5px;font-weight:600">View</a></td></tr>
                            <tr data-row data-search="s12040 nur aisyah itn3010" data-prog="BIT" data-sem="3" data-status="Pass" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3 text-slate-500" style="font-size:12.5px">S12040</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">Nur Aisyah</span></td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BIT</span></td><td class="px-6 py-3 text-slate-700 text-center" style="font-size:12.5px">3</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px"><span class="text-slate-900 font-medium">ITN3010</span> &middot; Cloud Networking</td><td class="px-6 py-3 text-center" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-amber-50 text-amber-700 border-amber-100" style="font-size:11.5px;font-weight:600">C</span></td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">2.00</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">2.30</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-emerald-50 text-emerald-700 border-emerald-100" style="font-size:11.5px;font-weight:600">Pass</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><a href="<%= ResolveUrl("~/admin/student_detail.aspx?id=S12040") %>" class="inline-flex h-7 items-center rounded-md border border-slate-200 bg-white px-2 text-slate-600 hover:bg-slate-50" style="font-size:11.5px;font-weight:600">View</a></td></tr>
                            <tr data-row data-search="s12041 raj kumar bba3201" data-prog="BBA" data-sem="5" data-status="Pass" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3 text-slate-500" style="font-size:12.5px">S12041</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">Raj Kumar</span></td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BBA</span></td><td class="px-6 py-3 text-slate-700 text-center" style="font-size:12.5px">5</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px"><span class="text-slate-900 font-medium">BBA3201</span> &middot; Strategic Marketing</td><td class="px-6 py-3 text-center" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">B+</span></td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">3.30</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">3.45</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-emerald-50 text-emerald-700 border-emerald-100" style="font-size:11.5px;font-weight:600">Pass</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><a href="<%= ResolveUrl("~/admin/student_detail.aspx?id=S12041") %>" class="inline-flex h-7 items-center rounded-md border border-slate-200 bg-white px-2 text-slate-600 hover:bg-slate-50" style="font-size:11.5px;font-weight:600">View</a></td></tr>
                            <tr data-row data-search="s12042 tan mei ling csc2030" data-prog="BCS" data-sem="2" data-status="Fail" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3 text-slate-500" style="font-size:12.5px">S12042</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">Tan Mei Ling</span></td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BCS</span></td><td class="px-6 py-3 text-slate-700 text-center" style="font-size:12.5px">2</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px"><span class="text-slate-900 font-medium">CSC2030</span> &middot; Machine Learning</td><td class="px-6 py-3 text-center" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-[#e0162b]/10 text-[#a01020] border-[#e0162b]/20" style="font-size:11.5px;font-weight:600">F</span></td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">0.00</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">1.80</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-[#e0162b]/10 text-[#a01020] border-[#e0162b]/20" style="font-size:11.5px;font-weight:600">Fail</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><a href="<%= ResolveUrl("~/admin/student_detail.aspx?id=S12042") %>" class="inline-flex h-7 items-center rounded-md border border-slate-200 bg-white px-2 text-slate-600 hover:bg-slate-50" style="font-size:11.5px;font-weight:600">View</a></td></tr>
                            <tr data-table-empty style="display:none"><td colspan="10" class="py-10 text-center text-slate-400" style="font-size:13px">No results match your filters.</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <%-- Pass/Fail --%>
        <div data-tab-panel="passfail">
            <div data-table data-page-size="20">
                <div class="flex flex-col gap-3 px-6 py-4 lg:flex-row lg:items-center lg:justify-between">
                    <div class="relative w-full lg:max-w-sm">
                        <svg viewBox="0 0 24 24" class="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7" /><path d="m21 21-4.3-4.3" /></svg>
                        <input data-table-search placeholder="Search course code or title&hellip;" class="h-9 w-full rounded-md border border-slate-200 bg-white pl-9 pr-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px" />
                    </div>
                    <div class="flex flex-wrap items-center gap-2">
                        <select data-table-filter="prog" class="h-9 rounded-md border border-slate-200 bg-white px-3 text-slate-700 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px"><%= ProgrammeOptionsHtml %></select>
                        <select data-table-filter="sem" class="h-9 rounded-md border border-slate-200 bg-white px-3 text-slate-700 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px"><%= SemesterOptionsHtml %></select>
                        <div data-table-chip="band" class="inline-flex items-center rounded-md border border-slate-200 bg-white p-0.5">
                            <button type="button" data-chip="All" data-active="true" class="rounded px-2.5 py-1 text-slate-600 hover:text-slate-900 data-[active=true]:bg-[#e0162b]/10 data-[active=true]:text-[#a01020]" style="font-size:11.5px;font-weight:600">All</button>
                            <button type="button" data-chip="High" class="rounded px-2.5 py-1 text-slate-600 hover:text-slate-900 data-[active=true]:bg-[#e0162b]/10 data-[active=true]:text-[#a01020]" style="font-size:11.5px;font-weight:600">High</button>
                            <button type="button" data-chip="Medium" class="rounded px-2.5 py-1 text-slate-600 hover:text-slate-900 data-[active=true]:bg-[#e0162b]/10 data-[active=true]:text-[#a01020]" style="font-size:11.5px;font-weight:600">Medium</button>
                            <button type="button" data-chip="Low" class="rounded px-2.5 py-1 text-slate-600 hover:text-slate-900 data-[active=true]:bg-[#e0162b]/10 data-[active=true]:text-[#a01020]" style="font-size:11.5px;font-weight:600">Low</button>
                        </div>
                    </div>
                </div>
                <div class="overflow-x-auto">
                    <table class="min-w-full">
                        <thead class="border-y border-slate-100 bg-slate-50/60 text-slate-500"><tr>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Code</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Course</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Prog</th><th class="px-6 py-3 text-center uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Sem</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Students</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Passed</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Failed</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Pass Rate</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Status</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Action</th>
                        </tr></thead>
                        <tbody>
                            <%= PassFailRowsHtml %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <%-- Attendance --%>
        <div data-tab-panel="attendance">
            <div data-table data-page-size="20">
                <div class="flex flex-col gap-3 px-6 py-4 lg:flex-row lg:items-center lg:justify-between">
                    <div class="relative w-full lg:max-w-sm">
                        <svg viewBox="0 0 24 24" class="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7" /><path d="m21 21-4.3-4.3" /></svg>
                        <input data-table-search placeholder="Search course code or title&hellip;" class="h-9 w-full rounded-md border border-slate-200 bg-white pl-9 pr-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px" />
                    </div>
                    <div class="flex flex-wrap items-center gap-2">
                        <select data-table-filter="prog" class="h-9 rounded-md border border-slate-200 bg-white px-3 text-slate-700 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px"><%= ProgrammeOptionsHtml %></select>
                        <div data-table-chip="status" class="inline-flex items-center rounded-md border border-slate-200 bg-white p-0.5">
                            <button type="button" data-chip="All" data-active="true" class="rounded px-2.5 py-1 text-slate-600 hover:text-slate-900 data-[active=true]:bg-[#e0162b]/10 data-[active=true]:text-[#a01020]" style="font-size:11.5px;font-weight:600">All</button>
                            <button type="button" data-chip="Healthy" class="rounded px-2.5 py-1 text-slate-600 hover:text-slate-900 data-[active=true]:bg-[#e0162b]/10 data-[active=true]:text-[#a01020]" style="font-size:11.5px;font-weight:600">Healthy</button>
                            <button type="button" data-chip="Warning" class="rounded px-2.5 py-1 text-slate-600 hover:text-slate-900 data-[active=true]:bg-[#e0162b]/10 data-[active=true]:text-[#a01020]" style="font-size:11.5px;font-weight:600">Warning</button>
                            <button type="button" data-chip="Critical" class="rounded px-2.5 py-1 text-slate-600 hover:text-slate-900 data-[active=true]:bg-[#e0162b]/10 data-[active=true]:text-[#a01020]" style="font-size:11.5px;font-weight:600">Critical</button>
                        </div>
                    </div>
                </div>
                <div class="overflow-x-auto">
                    <table class="min-w-full">
                        <thead class="border-y border-slate-100 bg-slate-50/60 text-slate-500"><tr>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Code</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Course</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Prog</th><th class="px-6 py-3 text-center uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Sem</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Enrolled</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Attendance</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Sessions</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Status</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Action</th>
                        </tr></thead>
                        <tbody>
                            <%= AttendanceRowsHtml %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <%-- At-Risk --%>
        <div data-tab-panel="atrisk">
            <div class="overflow-x-auto">
                <table class="min-w-full">
                    <thead class="border-y border-slate-100 bg-slate-50/60 text-slate-500"><tr>
                        <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">ID</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Name</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Prog</th><th class="px-6 py-3 text-center uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Sem</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">CGPA</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Attend.</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Failed</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Risk</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Reason</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Action</th>
                    </tr></thead>
                    <tbody>
                        <tr class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3 text-slate-500" style="font-size:12.5px">S12042</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">Tan Mei Ling</span></td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BCS</span></td><td class="px-6 py-3 text-slate-700 text-center" style="font-size:12.5px">2</td><td class="px-6 py-3 text-right text-[#a01020] font-semibold" style="font-size:12.5px">1.80</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">62%</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">2</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-[#e0162b]/10 text-[#a01020] border-[#e0162b]/20" style="font-size:11.5px;font-weight:600">Critical</span></td><td class="px-6 py-3 text-slate-700 max-w-xs truncate" style="font-size:12.5px">Low CGPA + low attendance</td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-2"><a href="<%= ResolveUrl("~/admin/student_detail.aspx?id=S12042") %>" class="inline-flex h-7 items-center rounded-md border border-slate-200 bg-white px-2 text-slate-600 hover:bg-slate-50" style="font-size:11.5px;font-weight:600">View</a><button type="button" data-modal-open="intervene-modal" class="inline-flex h-7 items-center rounded-md bg-[#e0162b] px-2 text-white hover:bg-[#a01020]" style="font-size:11.5px;font-weight:600">Intervene</button></div></td></tr>
                        <tr class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3 text-slate-500" style="font-size:12.5px">S12048</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">Ahmad Faizal</span></td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BIT</span></td><td class="px-6 py-3 text-slate-700 text-center" style="font-size:12.5px">3</td><td class="px-6 py-3 text-right text-[#a01020] font-semibold" style="font-size:12.5px">1.95</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">71%</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">1</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-[#e0162b]/10 text-[#a01020] border-[#e0162b]/20" style="font-size:11.5px;font-weight:600">High</span></td><td class="px-6 py-3 text-slate-700 max-w-xs truncate" style="font-size:12.5px">Below probation threshold</td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-2"><a href="<%= ResolveUrl("~/admin/student_detail.aspx?id=S12048") %>" class="inline-flex h-7 items-center rounded-md border border-slate-200 bg-white px-2 text-slate-600 hover:bg-slate-50" style="font-size:11.5px;font-weight:600">View</a><button type="button" data-modal-open="intervene-modal" class="inline-flex h-7 items-center rounded-md bg-[#e0162b] px-2 text-white hover:bg-[#a01020]" style="font-size:11.5px;font-weight:600">Intervene</button></div></td></tr>
                        <tr class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3 text-slate-500" style="font-size:12.5px">S12051</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">Choo Kah Yan</span></td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BBA</span></td><td class="px-6 py-3 text-slate-700 text-center" style="font-size:12.5px">4</td><td class="px-6 py-3 text-right text-[#a01020] font-semibold" style="font-size:12.5px">2.05</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">75%</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">1</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-amber-50 text-amber-700 border-amber-100" style="font-size:11.5px;font-weight:600">Medium</span></td><td class="px-6 py-3 text-slate-700 max-w-xs truncate" style="font-size:12.5px">Repeated course failure</td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-2"><a href="<%= ResolveUrl("~/admin/student_detail.aspx?id=S12051") %>" class="inline-flex h-7 items-center rounded-md border border-slate-200 bg-white px-2 text-slate-600 hover:bg-slate-50" style="font-size:11.5px;font-weight:600">View</a><button type="button" data-modal-open="intervene-modal" class="inline-flex h-7 items-center rounded-md bg-[#e0162b] px-2 text-white hover:bg-[#a01020]" style="font-size:11.5px;font-weight:600">Intervene</button></div></td></tr>
                    </tbody>
                </table>
            </div>
        </div>

        <%-- Top Performers --%>
        <div data-tab-panel="top">
            <div class="overflow-x-auto">
                <table class="min-w-full">
                    <thead class="border-y border-slate-100 bg-slate-50/60 text-slate-500"><tr>
                        <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">ID</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Name</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Prog</th><th class="px-6 py-3 text-center uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Sem</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">CGPA</th><th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Awards</th><th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Action</th>
                    </tr></thead>
                    <tbody>
                        <tr class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3 text-slate-500" style="font-size:12.5px">S12101</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">Lee Hui Min</span></td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BCS</span></td><td class="px-6 py-3 text-slate-700 text-center" style="font-size:12.5px">5</td><td class="px-6 py-3 text-right text-emerald-600 font-semibold" style="font-size:12.5px">3.95</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Dean's List &times; 3</td><td class="px-6 py-3 text-right" style="font-size:12.5px"><a href="<%= ResolveUrl("~/admin/student_detail.aspx?id=S12101") %>" class="inline-flex h-7 items-center rounded-md border border-slate-200 bg-white px-2 text-slate-600 hover:bg-slate-50" style="font-size:11.5px;font-weight:600">View</a></td></tr>
                        <tr class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3 text-slate-500" style="font-size:12.5px">S12108</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">Vivek Sharma</span></td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BDS</span></td><td class="px-6 py-3 text-slate-700 text-center" style="font-size:12.5px">4</td><td class="px-6 py-3 text-right text-emerald-600 font-semibold" style="font-size:12.5px">3.92</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Dean's List &times; 2</td><td class="px-6 py-3 text-right" style="font-size:12.5px"><a href="<%= ResolveUrl("~/admin/student_detail.aspx?id=S12108") %>" class="inline-flex h-7 items-center rounded-md border border-slate-200 bg-white px-2 text-slate-600 hover:bg-slate-50" style="font-size:11.5px;font-weight:600">View</a></td></tr>
                        <tr class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3 text-slate-500" style="font-size:12.5px">S12119</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">Farah Diana</span></td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BBA</span></td><td class="px-6 py-3 text-slate-700 text-center" style="font-size:12.5px">6</td><td class="px-6 py-3 text-right text-emerald-600 font-semibold" style="font-size:12.5px">3.88</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Dean's List &times; 4</td><td class="px-6 py-3 text-right" style="font-size:12.5px"><a href="<%= ResolveUrl("~/admin/student_detail.aspx?id=S12119") %>" class="inline-flex h-7 items-center rounded-md border border-slate-200 bg-white px-2 text-slate-600 hover:bg-slate-50" style="font-size:11.5px;font-weight:600">View</a></td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <%-- Intervene modal --%>
    <div id="intervene-modal" data-modal class="fixed inset-0 z-[60] items-center justify-center p-4" style="display:none">
        <div data-modal-backdrop class="absolute inset-0 bg-slate-900/40 backdrop-blur-sm"></div>
        <div class="relative w-full max-w-2xl max-h-[90vh] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl flex flex-col">
            <div class="flex items-start justify-between gap-4 border-b border-slate-100 px-6 py-4"><div><h2 class="text-slate-900" style="font-size:17px;font-weight:700;letter-spacing:-0.01em">Intervene</h2><p class="mt-0.5 text-slate-500" style="font-size:13px">Assign a mentor and schedule a follow-up meeting.</p></div><button type="button" data-modal-close class="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-400 hover:bg-slate-100 hover:text-slate-700"><i data-lucide="x" class="h-4 w-4"></i></button></div>
            <div class="flex-1 overflow-y-auto px-6 py-5">
                <div class="space-y-4">
                    <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Assign Mentor</span><div class="mt-1.5"><select class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px"><%= LecturerOptionsHtml %></select></div></label>
                    <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Meeting Date</span><div class="mt-1.5"><input type="date" class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px" /></div></label>
                    <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Notes</span><div class="mt-1.5"><textarea placeholder="Action plan&hellip;" class="w-full min-h-[88px] rounded-md border border-slate-200 bg-white px-3 py-2 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px;line-height:1.5"></textarea></div></label>
                </div>
            </div>
            <div class="flex items-center justify-end gap-2 border-t border-slate-100 px-6 py-4 bg-slate-50/40"><button type="button" data-modal-close class="inline-flex items-center gap-1.5 rounded-md border border-slate-200 bg-white px-3 h-10 text-slate-700 hover:bg-slate-50" style="font-size:13px;font-weight:600">Cancel</button><button type="button" data-modal-close data-toast="Intervention scheduling is not connected yet" data-toast-type="info" class="inline-flex items-center rounded-md bg-[#e0162b] px-4 h-10 text-white hover:bg-[#a01020]" style="font-size:13px;font-weight:600">Save intervention</button></div>
        </div>
    </div>

    <table class="hidden"><tbody id="backend-student-rows"><%= StudentRowsHtml %></tbody><tbody id="backend-risk-rows"><%= AtRiskRowsHtml %></tbody><tbody id="backend-top-rows"><%= TopPerformerRowsHtml %></tbody></table>
</asp:Content>
<asp:Content ContentPlaceHolderID="ScriptsPlaceholder" runat="server">
    <script src="<%= ResolveUrl("~/js/admin/shared/icons.js") %>"></script>
    <script src="<%= ResolveUrl("~/js/admin/shared/toast.js") %>"></script>
    <script src="<%= ResolveUrl("~/js/admin/shared/table.js") %>"></script>
    <script src="<%= ResolveUrl("~/js/admin/shared/ui.js") %>"></script>
    <script>
      (function () {
        function replaceRows(panel, sourceId) {
          var target = document.querySelector("[data-tab-panel='" + panel + "'] tbody");
          var source = document.getElementById(sourceId);
          if (!target || !source) return;
          Array.prototype.forEach.call(target.querySelectorAll("tr:not([data-table-empty])"), function (row) { row.remove(); });
          while (source.firstElementChild) target.insertBefore(source.firstElementChild, target.firstChild);
        }
        replaceRows("students", "backend-student-rows");
        replaceRows("atrisk", "backend-risk-rows");
        replaceRows("top", "backend-top-rows");
      })();
    </script>
</asp:Content>

