//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.shared
{
    public partial class AdminLayout
    {
        protected global::src.controls.admin_sidebar AdminSidebar1;
        protected global::src.controls.admin_topbar AdminTopbar1;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadPlaceholder;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ScriptsPlaceholder;
    }
}
