<%@ Page Language="C#" MasterPageFile="~/admin/AdminLayout.master" AutoEventWireup="true" CodeBehind="programme_course.aspx.cs" Inherits="src.admin.programme_course" Title="Programme & Course - INTI Admin Portal" %>
<asp:Content ContentPlaceHolderID="MainContent" runat="server">
<div data-tabs>

    <div class="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
        <div>
            <p class="text-slate-500" style="font-size:13px;font-weight:500">Admin</p>
            <h1 class="mt-1 text-slate-900" style="font-size:28px;font-weight:700;letter-spacing:-0.01em">Programme &amp; Course</h1>
            <p class="mt-1 text-slate-500" style="font-size:14px">Manage programmes, courses, and lecturer course assignments.</p>
        </div>
        <div class="flex flex-wrap items-center gap-2">
            <div class="relative" data-dropdown>
                <button type="button" data-dropdown-toggle class="inline-flex items-center gap-1.5 rounded-md border border-slate-200 bg-white px-3 h-10 text-slate-700 hover:bg-slate-50 transition-colors" style="font-size:13px;font-weight:600"><i data-lucide="download" class="h-4 w-4"></i> Export <i data-lucide="chevron-down" class="h-3.5 w-3.5"></i></button>
                <div data-dropdown-menu style="display:none" class="absolute right-0 z-20 mt-2 w-48 rounded-xl border border-slate-200 bg-white p-1 shadow-lg">
                    <button type="button" data-toast="PDF export started" data-toast-desc="Current list queued for download" class="flex w-full items-center gap-2 rounded-md px-3 py-2 text-left text-slate-700 hover:bg-slate-50" style="font-size:13px;font-weight:500"><i data-lucide="file-text" class="h-4 w-4 text-[#e0162b]"></i> Export as PDF</button>
                    <button type="button" data-toast="Excel export started" data-toast-desc="Current list queued for download" class="flex w-full items-center gap-2 rounded-md px-3 py-2 text-left text-slate-700 hover:bg-slate-50" style="font-size:13px;font-weight:500"><i data-lucide="file-spreadsheet" class="h-4 w-4 text-emerald-600"></i> Export as Excel</button>
                </div>
            </div>
            <span data-tab-panel="programmes"><button type="button" data-modal-open="prog-modal" class="inline-flex items-center gap-1.5 rounded-md bg-[#e0162b] px-4 h-10 text-white hover:bg-[#a01020] transition-colors shadow-[0_8px_18px_-10px_rgba(224,22,43,0.9)]" style="font-size:13px;font-weight:600"><i data-lucide="plus" class="h-4 w-4"></i> New Programme</button></span>
            <span data-tab-panel="courses"><button type="button" data-modal-open="course-modal" class="inline-flex items-center gap-1.5 rounded-md bg-[#e0162b] px-4 h-10 text-white hover:bg-[#a01020] transition-colors shadow-[0_8px_18px_-10px_rgba(224,22,43,0.9)]" style="font-size:13px;font-weight:600"><i data-lucide="plus" class="h-4 w-4"></i> New Course</button></span>
            <span data-tab-panel="assign"><button type="button" data-modal-open="assign-modal" class="inline-flex items-center gap-1.5 rounded-md bg-[#e0162b] px-4 h-10 text-white hover:bg-[#a01020] transition-colors shadow-[0_8px_18px_-10px_rgba(224,22,43,0.9)]" style="font-size:13px;font-weight:600"><i data-lucide="plus" class="h-4 w-4"></i> New Assignment</button></span>
        </div>
    </div>

    <section class="mt-6 rounded-lg border border-slate-200 bg-white">
        <div class="flex flex-wrap gap-1 border-b border-slate-100 px-4 pt-3">
            <button type="button" data-tab="programmes" class="inline-flex items-center gap-2 rounded-t-lg border-b-2 border-transparent px-3 py-2 text-slate-500 hover:text-slate-900 data-[active=true]:border-[#e0162b] data-[active=true]:text-[#a01020]" style="font-size:13px;font-weight:600">Programmes</button>
            <button type="button" data-tab="courses" class="inline-flex items-center gap-2 rounded-t-lg border-b-2 border-transparent px-3 py-2 text-slate-500 hover:text-slate-900 data-[active=true]:border-[#e0162b] data-[active=true]:text-[#a01020]" style="font-size:13px;font-weight:600">Courses</button>
            <button type="button" data-tab="assign" class="inline-flex items-center gap-2 rounded-t-lg border-b-2 border-transparent px-3 py-2 text-slate-500 hover:text-slate-900 data-[active=true]:border-[#e0162b] data-[active=true]:text-[#a01020]" style="font-size:13px;font-weight:600">Course Assignment</button>
        </div>

        <%-- Programmes tab --%>
        <div data-tab-panel="programmes">
            <div data-table data-page-size="20">
                <div class="flex flex-col gap-3 px-6 py-4 lg:flex-row lg:items-center lg:justify-between">
                    <div class="relative w-full lg:max-w-sm">
                        <svg viewBox="0 0 24 24" class="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7" /><path d="m21 21-4.3-4.3" /></svg>
                        <input data-table-search placeholder="Search&hellip;" class="h-9 w-full rounded-md border border-slate-200 bg-white pl-9 pr-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px" />
                    </div>
                    <select data-table-filter="status" class="h-9 rounded-md border border-slate-200 bg-white px-3 text-slate-700 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px"><option value="">All statuses</option><option>Active</option><option>Inactive</option><option>New</option></select>
                </div>
                <div class="overflow-x-auto">
                    <table class="min-w-full">
                        <thead class="border-y border-slate-100 bg-slate-50/60 text-slate-500"><tr>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Code</th>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Name</th>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Level</th>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Duration</th>
                            <th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Sems</th>
                            <th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Students</th>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Status</th>
                            <th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Action</th>
                        </tr></thead>
                        <tbody>
                            <tr data-row data-search="bcs bachelor of computer science" data-status="Active" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">BCS</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Bachelor of Computer Science</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Undergraduate</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">3 yrs</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">6</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">612</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-emerald-50 text-emerald-700 border-emerald-100" style="font-size:11.5px;font-weight:600">Active</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-1"><button type="button" data-drawer-open="view-prog" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="eye" class="h-3.5 w-3.5"></i></button><button type="button" data-modal-open="prog-modal" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="pencil" class="h-3.5 w-3.5"></i></button><button type="button" data-confirm data-confirm-title="Delete this record?" data-confirm-message="&quot;Bachelor of Computer Science&quot; will be permanently removed. This cannot be undone." data-confirm-label="Delete" data-confirm-danger="true" data-confirm-toast="Deleted" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[#e0162b] hover:bg-[#e0162b]/5"><i data-lucide="trash-2" class="h-3.5 w-3.5"></i></button></div></td></tr>
                            <tr data-row data-search="bit bachelor of information technology" data-status="Active" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">BIT</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Bachelor of Information Technology</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Undergraduate</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">3 yrs</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">6</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">504</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-emerald-50 text-emerald-700 border-emerald-100" style="font-size:11.5px;font-weight:600">Active</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-1"><button type="button" data-drawer-open="view-prog" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="eye" class="h-3.5 w-3.5"></i></button><button type="button" data-modal-open="prog-modal" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="pencil" class="h-3.5 w-3.5"></i></button><button type="button" data-confirm data-confirm-title="Delete this record?" data-confirm-message="&quot;Bachelor of Information Technology&quot; will be permanently removed. This cannot be undone." data-confirm-label="Delete" data-confirm-danger="true" data-confirm-toast="Deleted" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[#e0162b] hover:bg-[#e0162b]/5"><i data-lucide="trash-2" class="h-3.5 w-3.5"></i></button></div></td></tr>
                            <tr data-row data-search="bba bachelor of business administration" data-status="Active" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">BBA</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Bachelor of Business Administration</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Undergraduate</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">3 yrs</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">6</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">488</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-emerald-50 text-emerald-700 border-emerald-100" style="font-size:11.5px;font-weight:600">Active</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-1"><button type="button" data-drawer-open="view-prog" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="eye" class="h-3.5 w-3.5"></i></button><button type="button" data-modal-open="prog-modal" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="pencil" class="h-3.5 w-3.5"></i></button><button type="button" data-confirm data-confirm-title="Delete this record?" data-confirm-message="&quot;Bachelor of Business Administration&quot; will be permanently removed. This cannot be undone." data-confirm-label="Delete" data-confirm-danger="true" data-confirm-toast="Deleted" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[#e0162b] hover:bg-[#e0162b]/5"><i data-lucide="trash-2" class="h-3.5 w-3.5"></i></button></div></td></tr>
                            <tr data-row data-search="bme bachelor of mechanical engineering" data-status="Active" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">BME</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Bachelor of Mechanical Engineering</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Undergraduate</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">4 yrs</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">8</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">372</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-emerald-50 text-emerald-700 border-emerald-100" style="font-size:11.5px;font-weight:600">Active</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-1"><button type="button" data-drawer-open="view-prog" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="eye" class="h-3.5 w-3.5"></i></button><button type="button" data-modal-open="prog-modal" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="pencil" class="h-3.5 w-3.5"></i></button><button type="button" data-confirm data-confirm-title="Delete this record?" data-confirm-message="&quot;Bachelor of Mechanical Engineering&quot; will be permanently removed. This cannot be undone." data-confirm-label="Delete" data-confirm-danger="true" data-confirm-toast="Deleted" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[#e0162b] hover:bg-[#e0162b]/5"><i data-lucide="trash-2" class="h-3.5 w-3.5"></i></button></div></td></tr>
                            <tr data-row data-search="bds bachelor of data science" data-status="New" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">BDS</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Bachelor of Data Science</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Undergraduate</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">3 yrs</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">6</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">298</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-sky-50 text-sky-700 border-sky-100" style="font-size:11.5px;font-weight:600">New</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-1"><button type="button" data-drawer-open="view-prog" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="eye" class="h-3.5 w-3.5"></i></button><button type="button" data-modal-open="prog-modal" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="pencil" class="h-3.5 w-3.5"></i></button><button type="button" data-confirm data-confirm-title="Delete this record?" data-confirm-message="&quot;Bachelor of Data Science&quot; will be permanently removed. This cannot be undone." data-confirm-label="Delete" data-confirm-danger="true" data-confirm-toast="Deleted" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[#e0162b] hover:bg-[#e0162b]/5"><i data-lucide="trash-2" class="h-3.5 w-3.5"></i></button></div></td></tr>
                            <tr data-table-empty style="display:none"><td colspan="8" class="px-6 py-12 text-center text-slate-400" style="font-size:13px">No programmes match your filters.</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <%-- Courses tab --%>
        <div data-tab-panel="courses">
            <div data-table data-page-size="20">
                <div class="flex flex-col gap-3 px-6 py-4 lg:flex-row lg:items-center lg:justify-between">
                    <div class="relative w-full lg:max-w-sm">
                        <svg viewBox="0 0 24 24" class="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7" /><path d="m21 21-4.3-4.3" /></svg>
                        <input data-table-search placeholder="Search&hellip;" class="h-9 w-full rounded-md border border-slate-200 bg-white pl-9 pr-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px" />
                    </div>
                    <select data-table-filter="status" class="h-9 rounded-md border border-slate-200 bg-white px-3 text-slate-700 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px"><option value="">All statuses</option><option>Active</option><option>Inactive</option></select>
                </div>
                <div class="overflow-x-auto">
                    <table class="min-w-full">
                        <thead class="border-y border-slate-100 bg-slate-50/60 text-slate-500"><tr>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Code</th>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Title</th>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Programme</th>
                            <th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Credit</th>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Prerequisites</th>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Lecturer</th>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Status</th>
                            <th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Action</th>
                        </tr></thead>
                        <tbody>
                            <tr data-row data-search="csc1010 introduction to programming" data-status="Active" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">CSC1010</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Introduction to Programming</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BCS</span></td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">3</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-400" style="font-size:12px">None</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Dr. Hadi Yusof</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-emerald-50 text-emerald-700 border-emerald-100" style="font-size:11.5px;font-weight:600">Active</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-1"><button type="button" data-modal-open="course-modal" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="pencil" class="h-3.5 w-3.5"></i></button><button type="button" data-confirm data-confirm-title="Delete this record?" data-confirm-message="&quot;Introduction to Programming&quot; will be permanently removed. This cannot be undone." data-confirm-label="Delete" data-confirm-danger="true" data-confirm-toast="Deleted" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[#e0162b] hover:bg-[#e0162b]/5"><i data-lucide="trash-2" class="h-3.5 w-3.5"></i></button></div></td></tr>
                            <tr data-row data-search="csc2024 mobile app development" data-status="Active" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">CSC2024</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Mobile App Development</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BCS</span></td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">4</td><td class="px-6 py-3" style="font-size:12.5px"><div class="flex flex-wrap gap-1"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-sky-50 text-sky-700 border-sky-100" style="font-size:11.5px;font-weight:600">CSC1010</span></div></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Ms. Tan Mei Ling</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-emerald-50 text-emerald-700 border-emerald-100" style="font-size:11.5px;font-weight:600">Active</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-1"><button type="button" data-modal-open="course-modal" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="pencil" class="h-3.5 w-3.5"></i></button><button type="button" data-confirm data-confirm-title="Delete this record?" data-confirm-message="&quot;Mobile App Development&quot; will be permanently removed. This cannot be undone." data-confirm-label="Delete" data-confirm-danger="true" data-confirm-toast="Deleted" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[#e0162b] hover:bg-[#e0162b]/5"><i data-lucide="trash-2" class="h-3.5 w-3.5"></i></button></div></td></tr>
                            <tr data-row data-search="csc2030 machine learning fundamentals" data-status="Active" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">CSC2030</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Machine Learning Fundamentals</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BCS</span></td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">4</td><td class="px-6 py-3" style="font-size:12.5px"><div class="flex flex-wrap gap-1"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-sky-50 text-sky-700 border-sky-100" style="font-size:11.5px;font-weight:600">CSC1010</span></div></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Prof. Anand Kumar</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-emerald-50 text-emerald-700 border-emerald-100" style="font-size:11.5px;font-weight:600">Active</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-1"><button type="button" data-modal-open="course-modal" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="pencil" class="h-3.5 w-3.5"></i></button><button type="button" data-confirm data-confirm-title="Delete this record?" data-confirm-message="&quot;Machine Learning Fundamentals&quot; will be permanently removed. This cannot be undone." data-confirm-label="Delete" data-confirm-danger="true" data-confirm-toast="Deleted" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[#e0162b] hover:bg-[#e0162b]/5"><i data-lucide="trash-2" class="h-3.5 w-3.5"></i></button></div></td></tr>
                            <tr data-row data-search="itn3010 cloud networking" data-status="Active" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">ITN3010</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Cloud Networking</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BIT</span></td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">3</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-400" style="font-size:12px">None</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Dr. Lim Boon Keat</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-emerald-50 text-emerald-700 border-emerald-100" style="font-size:11.5px;font-weight:600">Active</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-1"><button type="button" data-modal-open="course-modal" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="pencil" class="h-3.5 w-3.5"></i></button><button type="button" data-confirm data-confirm-title="Delete this record?" data-confirm-message="&quot;Cloud Networking&quot; will be permanently removed. This cannot be undone." data-confirm-label="Delete" data-confirm-danger="true" data-confirm-toast="Deleted" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[#e0162b] hover:bg-[#e0162b]/5"><i data-lucide="trash-2" class="h-3.5 w-3.5"></i></button></div></td></tr>
                            <tr data-row data-search="bba1101 principles of management" data-status="Inactive" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">BBA1101</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Principles of Management</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BBA</span></td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">3</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-400" style="font-size:12px">None</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Ms. Aida Salleh</td><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">Inactive</span></td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-1"><button type="button" data-modal-open="course-modal" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="pencil" class="h-3.5 w-3.5"></i></button><button type="button" data-confirm data-confirm-title="Delete this record?" data-confirm-message="&quot;Principles of Management&quot; will be permanently removed. This cannot be undone." data-confirm-label="Delete" data-confirm-danger="true" data-confirm-toast="Deleted" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[#e0162b] hover:bg-[#e0162b]/5"><i data-lucide="trash-2" class="h-3.5 w-3.5"></i></button></div></td></tr>
                            <tr data-table-empty style="display:none"><td colspan="8" class="px-6 py-12 text-center text-slate-400" style="font-size:13px">No courses match your filters.</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <%-- Course Assignment tab --%>
        <div data-tab-panel="assign">
            <div data-table data-page-size="20">
                <div class="flex flex-col gap-3 px-6 py-4 lg:flex-row lg:items-center lg:justify-between">
                    <div class="relative w-full lg:max-w-sm">
                        <svg viewBox="0 0 24 24" class="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7" /><path d="m21 21-4.3-4.3" /></svg>
                        <input data-table-search placeholder="Search&hellip;" class="h-9 w-full rounded-md border border-slate-200 bg-white pl-9 pr-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:12.5px" />
                    </div>
                </div>
                <div class="overflow-x-auto">
                    <table class="min-w-full">
                        <thead class="border-y border-slate-100 bg-slate-50/60 text-slate-500"><tr>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Programme</th>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Semester</th>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Code</th>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Title</th>
                            <th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Credit</th>
                            <th class="px-6 py-3 text-left uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Lecturer</th>
                            <th class="px-6 py-3 text-right uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.05em">Action</th>
                        </tr></thead>
                        <tbody>
                            <tr data-row data-search="bcs csc1010 intro to programming dr. hadi yusof" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BCS</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Sem 1</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">CSC1010</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Intro to Programming</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">3</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Dr. Hadi Yusof</td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-1"><button type="button" data-modal-open="assign-modal" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="pencil" class="h-3.5 w-3.5"></i></button><button type="button" data-confirm data-confirm-title="Delete this record?" data-confirm-message="&quot;BCS &middot; CSC1010&quot; will be permanently removed. This cannot be undone." data-confirm-label="Delete" data-confirm-danger="true" data-confirm-toast="Deleted" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[#e0162b] hover:bg-[#e0162b]/5"><i data-lucide="trash-2" class="h-3.5 w-3.5"></i></button></div></td></tr>
                            <tr data-row data-search="bcs csc2024 mobile app dev ms. tan mei ling" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BCS</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Sem 4</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">CSC2024</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Mobile App Dev</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">4</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Ms. Tan Mei Ling</td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-1"><button type="button" data-modal-open="assign-modal" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="pencil" class="h-3.5 w-3.5"></i></button><button type="button" data-confirm data-confirm-title="Delete this record?" data-confirm-message="&quot;BCS &middot; CSC2024&quot; will be permanently removed. This cannot be undone." data-confirm-label="Delete" data-confirm-danger="true" data-confirm-toast="Deleted" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[#e0162b] hover:bg-[#e0162b]/5"><i data-lucide="trash-2" class="h-3.5 w-3.5"></i></button></div></td></tr>
                            <tr data-row data-search="bit itn3010 cloud networking dr. lim boon keat" class="border-b border-slate-100 hover:bg-slate-50/60"><td class="px-6 py-3" style="font-size:12.5px"><span class="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 bg-slate-100 text-slate-600 border-slate-200" style="font-size:11.5px;font-weight:600">BIT</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Sem 3</td><td class="px-6 py-3" style="font-size:12.5px"><span class="text-slate-900 font-medium">ITN3010</span></td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Cloud Networking</td><td class="px-6 py-3 text-slate-700 text-right" style="font-size:12.5px">3</td><td class="px-6 py-3 text-slate-700" style="font-size:12.5px">Dr. Lim Boon Keat</td><td class="px-6 py-3 text-right" style="font-size:12.5px"><div class="flex items-center justify-end gap-1"><button type="button" data-modal-open="assign-modal" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"><i data-lucide="pencil" class="h-3.5 w-3.5"></i></button><button type="button" data-confirm data-confirm-title="Delete this record?" data-confirm-message="&quot;BIT &middot; ITN3010&quot; will be permanently removed. This cannot be undone." data-confirm-label="Delete" data-confirm-danger="true" data-confirm-toast="Deleted" class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[#e0162b] hover:bg-[#e0162b]/5"><i data-lucide="trash-2" class="h-3.5 w-3.5"></i></button></div></td></tr>
                            <tr data-table-empty style="display:none"><td colspan="7" class="px-6 py-12 text-center text-slate-400" style="font-size:13px">No assignments match your filters.</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

</div>

<%-- Programme modal --%>
<div id="prog-modal" data-modal class="fixed inset-0 z-[60] items-center justify-center p-4" style="display:none">
    <div data-modal-backdrop class="absolute inset-0 bg-slate-900/40 backdrop-blur-sm"></div>
    <div class="relative w-full max-w-2xl max-h-[90vh] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl flex flex-col">
        <div class="flex items-start justify-between gap-4 border-b border-slate-100 px-6 py-4"><div><h2 class="text-slate-900" style="font-size:17px;font-weight:700;letter-spacing:-0.01em">Programme Details</h2></div><button type="button" data-modal-close class="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-400 hover:bg-slate-100 hover:text-slate-700"><i data-lucide="x" class="h-4 w-4"></i></button></div>
        <div class="flex-1 overflow-y-auto px-6 py-5">
            <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px">
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Code</span><div class="mt-1.5"><input class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px" /></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Name</span><div class="mt-1.5"><input class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px" /></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Level</span><div class="mt-1.5"><select class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px"><option>Undergraduate</option><option>Postgraduate</option><option>Foundation</option></select></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Duration</span><div class="mt-1.5"><input value="3 yrs" class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px" /></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Total Semesters</span><div class="mt-1.5"><input type="number" value="6" class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px" /></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Status</span><div class="mt-1.5"><select class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px"><option>Active</option><option>Inactive</option><option>New</option></select></div></label>
            </div>
            <div class="mt-5"><label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Description</span><div class="mt-1.5"><textarea placeholder="Programme overview, accreditation, career outcomes&hellip;" class="w-full min-h-[88px] rounded-md border border-slate-200 bg-white px-3 py-2 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px;line-height:1.5"></textarea></div></label></div>
        </div>
        <div class="flex items-center justify-end gap-2 border-t border-slate-100 px-6 py-4 bg-slate-50/40"><button type="button" data-modal-close class="inline-flex items-center rounded-md px-4 h-10 text-slate-600 hover:bg-slate-100" style="font-size:13px;font-weight:600">Cancel</button><button type="button" data-modal-close data-toast="Programme saved" class="inline-flex items-center rounded-md bg-[#e0162b] px-4 h-10 text-white hover:bg-[#a01020]" style="font-size:13px;font-weight:600">Save</button></div>
    </div>
</div>

<%-- Course modal --%>
<div id="course-modal" data-modal class="fixed inset-0 z-[60] items-center justify-center p-4" style="display:none">
    <div data-modal-backdrop class="absolute inset-0 bg-slate-900/40 backdrop-blur-sm"></div>
    <div class="relative w-full max-w-3xl max-h-[90vh] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl flex flex-col">
        <div class="flex items-start justify-between gap-4 border-b border-slate-100 px-6 py-4"><div><h2 class="text-slate-900" style="font-size:17px;font-weight:700;letter-spacing:-0.01em">Course Details</h2></div><button type="button" data-modal-close class="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-400 hover:bg-slate-100 hover:text-slate-700"><i data-lucide="x" class="h-4 w-4"></i></button></div>
        <div class="flex-1 overflow-y-auto px-6 py-5">
            <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px">
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Course Code</span><div class="mt-1.5"><input class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px" /></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Title</span><div class="mt-1.5"><input class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px" /></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Programme</span><div class="mt-1.5"><select class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px"><option>BCS &middot; Bachelor of Computer Science</option><option>BIT &middot; Bachelor of Information Technology</option><option>BBA &middot; Bachelor of Business Administration</option><option>BME &middot; Bachelor of Mechanical Engineering</option><option>BDS &middot; Bachelor of Data Science</option></select></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Credit Value</span><div class="mt-1.5"><input type="number" value="3" class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px" /></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Lecturer</span><div class="mt-1.5"><input class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px" /></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Status</span><div class="mt-1.5"><select class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px"><option>Active</option><option>Inactive</option></select></div></label>
            </div>
            <div class="mt-5">
                <span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Prerequisites</span>
                <div class="relative mt-1.5" data-dropdown>
                    <button type="button" data-dropdown-toggle class="flex h-9 w-full items-center justify-between rounded-md border border-slate-200 bg-white px-3 text-left text-slate-400 hover:border-slate-300" style="font-size:12.5px"><span>Select prerequisites&hellip;</span><i data-lucide="chevron-down" class="h-4 w-4 text-slate-400"></i></button>
                    <div data-dropdown-menu style="display:none" class="absolute left-0 right-0 z-20 mt-1 rounded-md border border-slate-200 bg-white shadow-lg">
                        <div class="border-b border-slate-100 px-3 py-2 text-slate-500" style="font-size:11.5px">Students must pass these courses before enrolling.</div>
                        <ul class="max-h-56 overflow-y-auto py-1">
                            <li><label class="flex w-full items-center gap-2 px-3 py-2 hover:bg-slate-50 cursor-pointer"><input type="checkbox" class="h-4 w-4 rounded border-slate-300 text-[#e0162b]" /><span class="text-slate-900 font-medium" style="font-size:13px">CSC1010</span><span class="text-slate-500" style="font-size:12.5px">Introduction to Programming</span></label></li>
                            <li><label class="flex w-full items-center gap-2 px-3 py-2 hover:bg-slate-50 cursor-pointer"><input type="checkbox" class="h-4 w-4 rounded border-slate-300 text-[#e0162b]" /><span class="text-slate-900 font-medium" style="font-size:13px">CSC2024</span><span class="text-slate-500" style="font-size:12.5px">Mobile App Development</span></label></li>
                            <li><label class="flex w-full items-center gap-2 px-3 py-2 hover:bg-slate-50 cursor-pointer"><input type="checkbox" class="h-4 w-4 rounded border-slate-300 text-[#e0162b]" /><span class="text-slate-900 font-medium" style="font-size:13px">CSC2030</span><span class="text-slate-500" style="font-size:12.5px">Machine Learning Fundamentals</span></label></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="flex items-center justify-end gap-2 border-t border-slate-100 px-6 py-4 bg-slate-50/40"><button type="button" data-modal-close class="inline-flex items-center rounded-md px-4 h-10 text-slate-600 hover:bg-slate-100" style="font-size:13px;font-weight:600">Cancel</button><button type="button" data-modal-close data-toast="Course saved" class="inline-flex items-center rounded-md bg-[#e0162b] px-4 h-10 text-white hover:bg-[#a01020]" style="font-size:13px;font-weight:600">Save</button></div>
    </div>
</div>

<%-- Assignment modal --%>
<div id="assign-modal" data-modal class="fixed inset-0 z-[60] items-center justify-center p-4" style="display:none">
    <div data-modal-backdrop class="absolute inset-0 bg-slate-900/40 backdrop-blur-sm"></div>
    <div class="relative w-full max-w-2xl max-h-[90vh] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl flex flex-col">
        <div class="flex items-start justify-between gap-4 border-b border-slate-100 px-6 py-4"><div><h2 class="text-slate-900" style="font-size:17px;font-weight:700;letter-spacing:-0.01em">Assignment Details</h2></div><button type="button" data-modal-close class="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-400 hover:bg-slate-100 hover:text-slate-700"><i data-lucide="x" class="h-4 w-4"></i></button></div>
        <div class="flex-1 overflow-y-auto px-6 py-5">
            <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px">
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Programme</span><div class="mt-1.5"><select class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px"><option>BCS</option><option>BIT</option><option>BBA</option><option>BME</option></select></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Semester</span><div class="mt-1.5"><select class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px"><option>Sem 1</option><option>Sem 2</option><option>Sem 3</option><option>Sem 4</option><option>Sem 5</option><option>Sem 6</option></select></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Course Code</span><div class="mt-1.5"><input class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px" /></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Title</span><div class="mt-1.5"><input class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px" /></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Credit</span><div class="mt-1.5"><input type="number" value="3" class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px" /></div></label>
                <label class="block"><span class="block text-slate-500 uppercase" style="font-size:11px;font-weight:600;letter-spacing:0.06em">Lecturer</span><div class="mt-1.5"><input class="h-10 w-full rounded-md border border-slate-200 bg-white px-3 outline-none focus:border-[#e0162b]/40 focus:ring-4 focus:ring-[#e0162b]/10" style="font-size:13px" /></div></label>
            </div>
        </div>
        <div class="flex items-center justify-end gap-2 border-t border-slate-100 px-6 py-4 bg-slate-50/40"><button type="button" data-modal-close class="inline-flex items-center rounded-md px-4 h-10 text-slate-600 hover:bg-slate-100" style="font-size:13px;font-weight:600">Cancel</button><button type="button" data-modal-close data-toast="Assignment saved" class="inline-flex items-center rounded-md bg-[#e0162b] px-4 h-10 text-white hover:bg-[#a01020]" style="font-size:13px;font-weight:600">Save</button></div>
    </div>
</div>

<%-- Programme view drawer --%>
<div id="view-prog" data-drawer class="fixed inset-0 z-[60]" style="display:none">
    <div data-drawer-backdrop class="absolute inset-0 bg-slate-900/40"></div>
    <div data-drawer-panel class="absolute right-0 top-0 h-full w-full max-w-xl bg-white shadow-2xl border-l border-slate-200 flex flex-col">
        <div class="flex items-start justify-between gap-4 border-b border-slate-100 px-6 py-4"><div><h2 class="text-slate-900" style="font-size:18px;font-weight:700;letter-spacing:-0.01em">Bachelor of Computer Science</h2><p class="mt-0.5 text-slate-500" style="font-size:13px">BCS</p></div><button type="button" data-drawer-close class="inline-flex h-8 w-8 items-center justify-center rounded-md text-slate-400 hover:bg-slate-100 hover:text-slate-700"><i data-lucide="x" class="h-4 w-4"></i></button></div>
        <div class="flex-1 overflow-y-auto px-6 py-5">
            <div class="grid gap-3">
                <div class="rounded-xl border border-slate-200 p-4"><div class="text-slate-500" style="font-size:11.5px;font-weight:600">Level</div><div class="mt-1 text-slate-900" style="font-size:14px">Undergraduate</div></div>
                <div class="rounded-xl border border-slate-200 p-4"><div class="text-slate-500" style="font-size:11.5px;font-weight:600">Duration</div><div class="mt-1 text-slate-900" style="font-size:14px">3 yrs</div></div>
                <div class="rounded-xl border border-slate-200 p-4"><div class="text-slate-500" style="font-size:11.5px;font-weight:600">Total Semesters</div><div class="mt-1 text-slate-900" style="font-size:14px">6</div></div>
                <div class="rounded-xl border border-slate-200 p-4"><div class="text-slate-500" style="font-size:11.5px;font-weight:600">Students Enrolled</div><div class="mt-1 text-slate-900" style="font-size:14px">612</div></div>
                <div class="rounded-xl border border-slate-200 p-4"><div class="text-slate-500" style="font-size:11.5px;font-weight:600">Status</div><div class="mt-1 text-slate-900" style="font-size:14px">Active</div></div>
            </div>
        </div>
        <div class="flex items-center justify-end gap-2 border-t border-slate-100 px-6 py-4 bg-slate-50/40"><button type="button" data-modal-open="prog-modal" data-drawer-close class="inline-flex items-center rounded-md border border-slate-200 bg-white px-3 h-10 text-slate-700 hover:bg-slate-50" style="font-size:13px;font-weight:600">Edit</button><button type="button" data-drawer-close class="inline-flex items-center rounded-md bg-[#e0162b] px-4 h-10 text-white hover:bg-[#a01020]" style="font-size:13px;font-weight:600">Close</button></div>
    </div>
</div>

</asp:Content>
<asp:Content ContentPlaceHolderID="ScriptsPlaceholder" runat="server">
    <script src="<%= ResolveUrl("~/js/admin/shared/icons.js") %>"></script>
    <script src="<%= ResolveUrl("~/js/admin/shared/toast.js") %>"></script>
    <script src="<%= ResolveUrl("~/js/admin/shared/table.js") %>"></script>
    <script src="<%= ResolveUrl("~/js/admin/shared/ui.js") %>"></script>
</asp:Content>
