//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.admin
{


    public partial class report_generator
    {

        /// <summary>
        /// hdnReportType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnReportType;

        /// <summary>
        /// ddlSemester control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlSemester;

        /// <summary>
        /// ddlProgramme control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlProgramme;

        /// <summary>
        /// ddlStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>
        /// ddlProgrammeStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlProgrammeStatus;

        /// <summary>
        /// rptPreview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptPreview;

        /// <summary>
        /// litPreviewCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litPreviewCount;

        /// <summary>
        /// btnStudentPrev control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnStudentPrev;

        /// <summary>
        /// btnStudentNext control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnStudentNext;

        /// <summary>
        /// emptyPreviewPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder emptyPreviewPanel;

        /// <summary>
        /// rptProgrammePreview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptProgrammePreview;

        /// <summary>
        /// litProgrammePreviewCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litProgrammePreviewCount;

        /// <summary>
        /// btnProgrammePrev control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnProgrammePrev;

        /// <summary>
        /// btnProgrammeNext control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnProgrammeNext;

        /// <summary>
        /// emptyProgrammePreviewPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder emptyProgrammePreviewPanel;

        /// <summary>
        /// rptCoursePreview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptCoursePreview;

        /// <summary>
        /// litCoursePreviewCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litCoursePreviewCount;

        /// <summary>
        /// btnCoursePrev control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnCoursePrev;

        /// <summary>
        /// btnCourseNext control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnCourseNext;

        /// <summary>
        /// emptyCoursePreviewPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder emptyCoursePreviewPanel;

        /// <summary>
        /// rptAttendancePreview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptAttendancePreview;

        /// <summary>
        /// litAttendancePreviewCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litAttendancePreviewCount;

        /// <summary>
        /// btnAttendancePrev control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAttendancePrev;

        /// <summary>
        /// btnAttendanceNext control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAttendanceNext;

        /// <summary>
        /// emptyAttendancePreviewPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder emptyAttendancePreviewPanel;

        /// <summary>
        /// rptAtRiskPreview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptAtRiskPreview;

        /// <summary>
        /// litAtRiskPreviewCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litAtRiskPreviewCount;

        /// <summary>
        /// btnAtRiskPrev control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAtRiskPrev;

        /// <summary>
        /// btnAtRiskNext control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAtRiskNext;

        /// <summary>
        /// emptyAtRiskPreviewPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder emptyAtRiskPreviewPanel;

    }
}
